# Amazon Scaping Laptops Data

In [160]:
# install beautifulsoup4 and requests
!pip install beautifulsoup4 requests

Requirement already satisfied: beautifulsoup4 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (4.14.3)
Requirement already satisfied: requests in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (2.32.5)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from beautifulsoup4) (4.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ssart\anaconda3\envs\ai-health\lib\site-packages (from requests) (2025.8.3)

In [161]:
# import required libraries
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

In [162]:
# url of the page to be scraped
url ="https://www.amazon.in/s?k=laptops&crid=3O5DJEZW2W1BU&sprefix=lapto%2Caps%2C809&ref=nb_sb_noss_2"

In [163]:
# make header to mimic a browser visit
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}

In [164]:
# check if the url is accessible
response = requests.get(url, headers=headers)
if response.status_code == 200:
    print("URL is accessible")
else:
    print("URL is not accessible")

URL is accessible

In [165]:
# check the response content
print(response.content)

b'<!doctype html><html lang="en-in" class="a-no-js" data-19ax5a9jf="dingo"><!-- sp:feature:head-start -->\n<head><script>var aPageStart = (new Date()).getTime();</script><meta charset="utf-8"/>\n<!-- sp:end-feature:head-start -->\n<!-- sp:feature:csm:head-open-part1 -->\n\n<script type=\'text/javascript\'>var ue_t0=ue_t0||+new Date();</script>\n<!-- sp:end-feature:csm:head-open-part1 -->\n<!-- sp:feature:cs-optimization -->\n<meta http-equiv=\'x-dns-prefetch-control\' content=\'on\'>\n<link rel="preconnect" href="https://images-eu.ssl-images-amazon.com" crossorigin>\n<link rel="preconnect" href="https://m.media-amazon.com" crossorigin>\n<!-- sp:end-feature:cs-optimization -->\n<!-- sp:feature:csm:head-open-part2 -->\n<script type=\'text/javascript\'>\nwindow.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;\nif (window.ue_ihb === 1) {\n\nvar ue_csm = window,\n    ue_hob = +new Date();\n(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);\n\n\n    var ue_err_chan = \'jserr\';\n(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,\npec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);\n\n\nvar ue_id = \'ZWT96F6H1ZV6JQ3CP7D3\',\n    ue_url = \'/rd/uedata\',\n    ue_drfp = true,\n    ue_navtiming = 1,\n    ue_mid = \'A21TJRUUN4KGV\',\n    ue_sid = \'525-0246536-9377368\',\n    ue_sn = \'www.amazon.in\',\n    ue_furl = \'fls-eu.amazon.in\',\n    ue_surl = \'https://unagi.amazon.in/1/events/com.amazon.csm.nexusclient.prod\',\n    ue_int = 0,\n    ue_fcsn = 1,\n    ue_urt = 3,\n    ue_rpl_ns = \'cel-rpl\',\n    ue_ddq = 1,\n    ue_fpf = \'//fls-eu.amazon.in/1/batch/1/OP/A21TJRUUN4KGV:525-0246536-9377368:ZWT96F6H1ZV6JQ3CP7D3$uedata=s:\',\n    ue_sbuimp = 1,\n    ue_ibft = 0,\n    ue_lpsi = 6000,\n    ue_lob = \'1\',\n    ue_act = \'-1\',\n    ue_dsbl_cel = 1,\n    ue_awsscrid = 1,\n\n    ue_swi = 1;\nvar ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=\nv[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;\n\n(function(d,k,R){function I(a){return a&&a.replace&&a.replace(/^\\s+|\\s+$/g,"")}function w(a){return"undefined"===typeof a}function M(a){return"function"===typeof a}function G(a,b){for(var c in b)b[x](c)&&(a[c]=b[c])}function N(a){try{var b=R.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function S(l,b,c){var s=(E||{}).type;if("device"!==c||2!==s&&1!==s){if(l){d.ue_id=a.id=a.rid=l;if("device"===c||"pre-fetch"===c)a.oid=I(l);p&&(p=p.replace(/((.*?:){2})(\\w+)/,function(a,\nb){return b+l}));J&&(e("id",J,l),J=0)}b&&(p&&(p=p.replace(/(.*?:)(\\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=p}}function T(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[x](c)&&b.push(c);return b}}function F(d,b,c,s){s=s||+new K;var f,k;if(b||w(c)){if(d)for(k in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=s,c)c[x](k)&&e(k,b,c[k]);return s}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(U=1);return e[d]=c||e[d]}function V(d,\nb,c,e,k){c="on"+c;var f=b[c];M(f)?d&&(a.h[d]=f):f=function(){};b[c]=function(a){k?(e(a),f(a)):(f(a),e(a))};b[c]&&(b[c].isUeh=1)}function W(l,b,c,s){function z(b,c,g){b=[b];var f=0,s={},m,h;u.latency={};c?(b.push("m=1"),s[c]=1):s=a.sc;for(h in s)if(s[x](h)){var z=e("wb",h),n=e("t",h)||{},v=e("t0",h)||a.t0,r,q;if(c||2==z){r=z?f++:"";b.push("sc"+r+"="+h);var p=A,t=A;2==z&&k.csa?(t=(p=d.ue_awsscrid?k.csa("Content",{element:{type:"scope",slotId:h,csmRequestId:""+g}}):k.csa("Content",{element:{type:"scope",\nslotId:h}}))&&M(p))&&+v&&p("mark","t0",+v):p=t=A;for(q in n)w(n[q])||null===n[q]||(b.push(q+r+"="+(n[q]-v)),t&&p("mark",X[q]||q,+n[q]));b.push("t"+r+"="+n[l]);u.latency["t"+r]=n[l];if(e("ctb",h)||e("wb",h))m=1}}!D&&m&&b.push("ctb=1");return b.join("&")}function v(b,c,g,e,l){if(!(!b||d.ue_swsfp&&e)){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!l&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));p?(l=k.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+\nl(b)+":"+(+new K-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&f.startTimer();a.b&&(f=a.b,a.b="",v(f,c,g,1))}}function r(b){var c=E?E.type:A,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!U||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),w(a.isNRBF)&&(d=a.ssw(a.oid),d.e||w(d.val)||(a.isNRBF=1<d.val?0:1)),w(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+\na.isBFT);return b}if(!a.paused&&(b||w(c))){for(var m in c)c[x](m)&&e(m,b,c[m]);a.isBFonMshop||F("pc",b,c);m="ld"===l&&b&&e("wb",b);var B=!d.ue_swsfp||!m,n=e("id",b)||a.id;m||n===a.oid||(J=b,ga(n,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var C=e("id",b)||a.id,q=e("id2",b)||d.ue_id2,g=a.url+"?"+l+"&v="+a.v+"&id="+C,D=e("ctb",b)||e("wb",b),u={eventName:l,version:a.v,id:C,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},t;D&&(g+="&ctb="+D);q&&(g+="&id2="+q);1<d.ueinit&&\n(g+="&ic="+d.ueinit);if(!("ld"!=l&&"ul"!=l||b&&b!=C)){if("ld"==l){try{k[O]&&k[O].isUeh&&(k[O]=null)}catch(N){}if(k.chrome)for(q=0;q<P.length;q++)Y(L,P[q]);(q=R.ue_backdetect)&&q.ue_back&&q.ue_back.value++;d._uess&&(t=d._uess());a.isl=1}B&&a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",C,"1"),a.isBFonMshop||F("tc",A,A,Q));B&&H&&!a.isBFonMshop&&!Z&&(f&&G(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,\n_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:(M(H.now)&&!w(Q)?new K(Q+H.now())-new K:0)+a.t0}),E&&G(a.t,{ty:E.type+a.t0,rc:E.redirectCount+a.t0}),Z=1);a.isBFonMshop||G(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",u.ifr=!0)}F(l,b,c,\ns);var y,h;m||b&&b!==C||ha(b);c=d.ue_mbl;B&&c&&c.cnt&&!m&&(g+=c.cnt());m?e("wb",b,2):"ld"==l&&(a.lid=I(C));for(y in a.sc)if(1==e("wb",y))break;if(m){if(a.s)return;g=z(g,null,n)}else c=z(g,null,n),c!=g&&(c=r(c),a.b=c),t&&(g+=t),g=z(g,b||a.id,n);g=r(g);if(a.b||m)for(y in a.sc)2==e("wb",y)&&delete a.sc[y];y=0;B&&a._rt&&(g+="&rt="+a._rt());t=k.csa;if(!m&&t)for(h in n=e("t",b)||{},c=t("PageTiming"),n)n[x](h)&&c("mark",X[h]||h,n[h]);m||(a.s=0,(h=d.ue_err)&&0<h.ec&&h.pec<h.ec&&(h.pec=h.ec,g+="&ec="+h.ec+\n"&ecf="+h.ecf),y=e("ctb",b),"ld"!==l||b||a.markers?a.markers&&a.isl&&!m&&b&&G(a.markers,e("t",b)):(a.markers={},G(a.markers,e("t",b))),e("t",b,{}));B&&a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),u.csmtags=a.tag(),a.tag=T());h=a.viz||[];n=h.length;B&&n&&(h=h.splice(0,n),g+="&viz="+h.join("|"),u.viz=h);w(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,u.pty=d.ue_pty,u.spty=d.ue_spty,u.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!B||!a._ui||b&&\nb!=C||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;v(g,l,y,m,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));m||(u.lob=d.ue_lob||"0",u.browserData=g,(b=t&&t("UEData"))&&b("log",u))}}function ha(a){var b=k.ue_csm_markers||{},c;for(c in b)b[x](c)&&F(c,a,A,b[c])}function D(a,b,c){c=c||k;if(c[$])c[$](a,b,!1);else if(c[aa])c[aa]("on"+a,b)}function Y(a,b,c){c=c||k;if(c[ba])c[ba](a,b,!1);else if(c[ca])c[ca]("on"+a,b)}function da(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,W(a))}}\nvar c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};k.chrome?(D(L,a),P.push(a)):e[L]=d.onUl;for(f in e)e[x](f)&&V(0,k,f,e[f]);d.ue_viz&&ue_viz();D("load",d.onLd);F("ue")}function ga(e,b,c,f,p){var v=d.ue_mbl,r=k.csa,m=r&&r("SPA"),r=r&&r("PageTiming");v&&v.ajax&&v.ajax(b,c);m&&r&&(e={requestId:e,transitionType:"soft"},"string"===typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof p&&(e.subPageType=p,d.ue_spty=p),m("newPage",e),r("mark","transitionStart",b));a.tag("ajax-transition")}\nd.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=k.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.348446.0";a.paused=!1;var x="hasOwnProperty",L="beforeunload",O="on"+L,$="addEventListener",ba="removeEventListener",aa="attachEvent",ca="detachEvent",X={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},K=k.Date,H=k.performance||\nk.webkitPerformance,f=(H||{}).timing,E=(H||{}).navigation,Q=(f||{}).navigationStart,p=d.ue_fpf,U=0,Z=0,P=[],J=0,A;a.oid=I(a.id);a.lid=I(a.id);a._t0=a.t0;a.tag=T();a.ifr=k.top!==k.self||k.frameElement?1:0;a.markers=null;a.attach=D;a.detach=Y;if("000-0000000-8675309"===d.ue_sid){var ea=N("cdn-rid"),fa=N("session-id");ea&&fa&&S(ea,fa,"cdn")}d.uei=da;d.ueh=V;d.ues=e;d.uet=F;d.uex=W;a.reset=S;a.pause=function(d){a.paused=d};da()})(ue_csm,ue_csm.window,ue_csm.document);\n\n\nue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");\n\nue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");\n(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);\n\n\n\nvar ue_hoe = +new Date();\n}\nwindow.ueinit = window.ue_ihb;\n</script>\n\n<!-- 4wnx8qt9ur6o -->\n<script>window.ue && ue.count && ue.count(\'CSMLibrarySize\', 10684)</script>\n<!-- sp:end-feature:csm:head-open-part2 -->\n<!-- sp:feature:aui-assets -->\n<link rel="stylesheet" href="https://m.media-amazon.com/images/I/21uDPuQuYwL._RC|51SvmD+jTBL.css_.css?AUIClients/AmazonUI" />\n<link rel="stylesheet" href="https://m.media-amazon.com/images/I/11WsGYSItxL._RC|01DE6WSvLKL.css,41ixaNR85ML.css,3182OVlP7IL.css,21JMC7OC91L.css,01xH+fhFIJL.css,0168Xo81wHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21D3IemrALL.css,11pDJV08stL.css,51yqRfvysvL.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11FeoxrgiyL.css,21TxBPhrLyL.css,01rSTIgNJIL.css,21Dt9D2TuML.css,31GD5I7tbCL.css,01i092IYHUL.css,01oaPOLX+-L.css,31Qk3MvcMIL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21GcfcmbahL.css,21OD8FuBraL.css,11XozyxiH7L.css,21n1oEPZnHL.css,11HVvPbE6JL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11TZSntL0oL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31un+UKeIeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#not-trident" />\n<script>\n(function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(c,e,I,B){"use strict";c._pd=function(){var a,u;return function(C,f,h,k,b,D,v,E,F){function w(d){try{return d()}catch(J){return!1}}function l(){if(m){var d={w:c.innerWidth||b.clientWidth,h:c.innerHeight||b.clientHeight};5<Math.abs(d.w-q.w)||50<d.h-q.h?(q=d,n=4,(d=a.mobile||a.tablet?450<d.w&&d.w>d.h:1250<=d.w)?k(b,"a-ws"):b.className=v(b,"a-ws")):0<n&&(n--,x=setTimeout(l,16))}}function G(d){(m=d===B?!m:!!d)&&l()}function H(){return m}if(!u){u=!0;var r=function(){var d=["O","ms","Moz","Webkit"],\nc=e.createElement("div");return{testGradients:function(){return!0},test:function(a){var b=a.charAt(0).toUpperCase()+a.substr(1);a=(d.join(b+" ")+b+" "+a).split(" ");for(b=a.length;b--;)if(""===c.style[a[b]])return!0;return!1},testTransform3d:function(){return!0}}}(),y=b.className,z=/(^| )a-mobile( |$)/.test(y),A=/(^| )a-tablet( |$)/.test(y);a={audio:function(){return!!e.createElement("audio").canPlayType},video:function(){return!!e.createElement("video").canPlayType},canvas:function(){return!!e.createElement("canvas").getContext},\nsvg:function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in e.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!c.history||!c.history.pushState)},webworker:function(){return!!c.Worker},autofocus:function(){return"autofocus"in e.createElement("input")},\ninputPlaceholder:function(){return"placeholder"in e.createElement("input")},textareaPlaceholder:function(){return"placeholder"in e.createElement("textarea")},localStorage:function(){return"localStorage"in c&&null!==c.localStorage},orientation:function(){return"orientation"in c},touch:function(){return"ontouchend"in e},gradients:function(){return r.testGradients()},hires:function(){var a=c.devicePixelRatio&&1.5<=c.devicePixelRatio||c.matchMedia&&c.matchMedia("(min-resolution:144dpi)").matches;E("hiRes"+\n(z?"Mobile":A?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return r.testTransform3d()},touchScrolling:function(){return f(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return f(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!f(/trident|Edge/i)},android:function(){return f(/android.([1-9]|[L-Z])/i)&&!f(/trident|Edge/i)},mobile:function(){return z},\ntablet:function(){return A},rtl:function(){return"rtl"===b.dir}};for(var g in a)a.hasOwnProperty(g)&&(a[g]=w(a[g]));for(var t="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),p=0;p<t.length;p++)a[t[p]]=w(function(){return r.test(t[p])});var m=!0,x=0,q={w:0,h:0},n=4;l();h(c,"resize",function(){clearTimeout(x);n=4;l()});b.className=v(b,"a-no-js");k(b,"a-js");!f(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||c.navigator.standalone||f(/safari/i)||k(b,"a-ember");\nh=[];for(g in a)a.hasOwnProperty(g)&&a[g]&&h.push("a-"+g.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));k(b,h.join(" "));b.setAttribute("data-aui-build-date",F);C.register("p-detect",function(){return{capabilities:a,localStorage:a.localStorage&&D,toggleResponsiveGrid:G,responsiveGridEnabled:H}});return a||{}}}}()})(window,document,Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===\nd||"require"===d)a.P.error(\'"module" or "require" injection is not supported.\');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with \'@amzn/\'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,C,D){function K(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function L(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function p(a,b,c,f){b=b&&c?b+a+c:b||c;return f?p(a,b,f):b}function y(a,b,c){try{Object.defineProperty(a,b,{value:c,writable:!1})}catch(f){a[b]=c}return c}function M(a,b){a.className=\nN(a,b)+" "+b}function N(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function aa(a,b,c){var f=c=a.length,e=function(){f--||(E.push(b),F||(m?m.set(z):setTimeout(z,0),F=!0))};for(e();c--;)O[a[c]]?e():(u[a[c]]=u[a[c]]||[]).push(e)}function ba(a,b,c,f,e){var d=h.createElement(a?"script":"link");x(d,"error",f);e&&x(d,"load",e);a?(d.type="text/javascript",d.async=!0,c&&/AUIClients|images[/]I/.test(b)&&d.setAttribute("crossorigin","anonymous"),d.src=b):(d.rel="stylesheet",\nd.href=b);h.getElementsByTagName("head")[0].appendChild(d)}function P(a,b){return function(c,f){function e(){ba(b,c,d,function(b){G?q("resource_unload"):d?(d=!1,q("resource_retry"),e()):(q("resource_error"),a.log("Asset failed to load: "+c));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},f)}if(Q[c])return!1;Q[c]=!0;q("resource_count");var d=!0;return!e()}}function ca(a,b,c){for(var f={name:a,guard:function(c){return b.guardFatal(a,c)},guardTime:function(a){return b.guardTime(a)},\nlogError:function(c,d,e){b.logError(c,d,e,a)}},e=[],d=0;d<c.length;d++)A.hasOwnProperty(c[d])&&(e[d]=H.hasOwnProperty(c[d])?H[c[d]](A[c[d]],f):A[c[d]]);return e}function v(a,b,c,f,e){return function(d,k){function n(){var a=null;f?a=k:"function"===typeof k&&(q.start=r(),a=k.apply(g,ca(d,h,l)),q.end=r());if(b){A[d]=a;a=d;for(O[a]=!0;(u[a]||[]).length;)u[a].shift()();delete u[a]}q.done=!0}var h=e||this;"function"===typeof d&&(k=d,d=D);b&&(d=d?d.replace(R,""):"__NONAME__",I.hasOwnProperty(d)&&h.error(p(", reregistered by ",\np(" by ",d+" already registered",I[d]),h.attribution),d),I[d]=h.attribution);for(var l=[],m=0;m<a.length;m++)l[m]=a[m].replace(R,"");var q=w[d||"anon"+ ++da]={depend:l,registered:r(),namespace:h.namespace};d&&ea.hasOwnProperty(d);c?n():aa(l,h.guardFatal(d,n),d);return{decorate:function(a){H[d]=h.guardFatal(d,a)}}}}function S(a){return function(){var b=Array.prototype.slice.call(arguments);return{ex

In [166]:
# convert the response content to a BeautifulSoup object
soup = BeautifulSoup(response.content, "html.parser")
soup

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-in"><!-- sp:feature:head-start -->
<head><script>var aPageStart = (new Date()).getTime();</script><meta charset="utf-8"/>
<!-- sp:end-feature:head-start -->
<!-- sp:feature:csm:head-open-part1 -->
<script type="text/javascript">var ue_t0=ue_t0||+new Date();</script>
<!-- sp:end-feature:csm:head-open-part1 -->
<!-- sp:feature:cs-optimization -->
<meta content="on" http-equiv="x-dns-prefetch-control"/>
<link crossorigin="" href="https://images-eu.ssl-images-amazon.com" rel="preconnect"/>
<link crossorigin="" href="https://m.media-amazon.com" rel="preconnect"/>
<!-- sp:end-feature:cs-optimization -->
<!-- sp:feature:csm:head-open-part2 -->
<script type="text/javascript">
window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = 'ZWT96F6H1ZV6JQ3CP7D3',
    ue_url = '/rd/uedata',
    ue_drfp = true,
    ue_navtiming = 1,
    ue_mid = 'A21TJRUUN4KGV',
    ue_sid = '525-0246536-9377368',
    ue_sn = 'www.amazon.in',
    ue_furl = 'fls-eu.amazon.in',
    ue_surl = 'https://unagi.amazon.in/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-eu.amazon.in/1/batch/1/OP/A21TJRUUN4KGV:525-0246536-9377368:ZWT96F6H1ZV6JQ3CP7D3$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_lpsi = 6000,
    ue_lob = '1',
    ue_act = '-1',
    ue_dsbl_cel = 1,
    ue_awsscrid = 1,

    ue_swi = 1;
var ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=
v[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;

(function(d,k,R){function I(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function w(a){return"undefined"===typeof a}function M(a){return"function"===typeof a}function G(a,b){for(var c in b)b[x](c)&&(a[c]=b[c])}function N(a){try{var b=R.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function S(l,b,c){var s=(E||{}).type;if("device"!==c||2!==s&&1!==s){if(l){d.ue_id=a.id=a.rid=l;if("device"===c||"pre-fetch"===c)a.oid=I(l);p&&(p=p.replace(/((.*?:){2})(\w+)/,function(a,
b){return b+l}));J&&(e("id",J,l),J=0)}b&&(p&&(p=p.replace(/(.*?:)(\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=p}}function T(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[x](c)&&b.push(c);return b}}function F(d,b,c,s){s=s||+new K;var f,k;if(b||w(c)){if(d)for(k in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=s,c)c[x](k)&&e(k,b,c[k]);return s}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(U=1);return e[d]=c||e[d]}function V(d,
b,c,e,k){c="on"+c;var f=b[c];M(f)?d&&(a.h[d]=f):f=function(){};b[c]=function(a){k?(e(a),f(a)):(f(a),e(a))};b[c]&&(b[c].isUeh=1)}function W(l,b,c,s){function z(b,c,g){b=[b];var f=0,s={},m,h;u.latency={};c?(b.push("m=1"),s[c]=1):s=a.sc;for(h in s)if(s[x](h)){var z=e("wb",h),n=e("t",h)||{},v=e("t0",h)||a.t0,r,q;if(c||2==z){r=z?f++:"";b.push("sc"+r+"="+h);var p=A,t=A;2==z&&k.csa?(t=(p=d.ue_awsscrid?k.csa("Content",{element:{type:"scope",slotId:h,csmRequestId:""+g}}):k.csa("Content",{element:{type:"scope",
slotId:h}}))&&M(p))&&+v&&p("mark","t0",+v):p=t=A;for(q in n)w(n[q])||null===n[q]||(b.push(q+r+"="+(n[q]-v)),t&&p("mark",X[q]||q,+n[q]));b.push("t"+r+"="+n[l]);u.latency["t"+r]=n[l];if(e("ctb",h)||e("wb",h))m=1}}!D&&m&&b.push("ctb=1");return b.join("&")}function v(b,c,g,e,l){if(!(!b||d.ue_swsfp&&e)){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!l&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));p?(l=k.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+
l(b)+":"+(+new K-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&f.startTimer();a.b&&(f=a.b,a.b="",v(f,c,g,1))}}function r(b){var c=E?E.type:A,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!U||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),w(a.isNRBF)&&(d=a.ssw(a.oid),d.e||w(d.val)||(a.isNRBF=1<d.val?0:1)),w(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+
a.isBFT);return b}if(!a.paused&&(b||w(c))){for(var m in c)c[x](m)&&e(m,b,c[m]);a.isBFonMshop||F("pc",b,c);m="ld"===l&&b&&e("wb",b);var B=!d.ue_swsfp||!m,n=e("id",b)||a.id;m||n===a.oid||(J=b,ga(n,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var C=e("id",b)||a.id,q=e("id2",b)||d.ue_id2,g=a.url+"?"+l+"&v="+a.v+"&id="+C,D=e("ctb",b)||e("wb",b),u={eventName:l,version:a.v,id:C,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},t;D&&(g+="&ctb="+D);q&&(g+="&id2="+q);1<d.ueinit&&
(g+="&ic="+d.ueinit);if(!("ld"!=l&&"ul"!=l||b&&b!=C)){if("ld"==l){try{k[O]&&k[O].isUeh&&(k[O]=null)}catch(N){}if(k.chrome)for(q=0;q<P.length;q++)Y(L,P[q]);(q=R.ue_backdetect)&&q.ue_back&&q.ue_back.value++;d._uess&&(t=d._uess());a.isl=1}B&&a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",C,"1"),a.isBFonMshop||F("tc",A,A,Q));B&&H&&!a.isBFonMshop&&!Z&&(f&&G(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,
_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:(M(H.now)&&!w(Q)?new K(Q+H.now())-new K:0)+a.t0}),E&&G(a.t,{ty:E.type+a.t0,rc:E.redirectCount+a.t0}),Z=1);a.isBFonMshop||G(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",u.ifr=!0)}F(l,b,c,
s);var y,h;m||b&&b!==C||ha(b);c=d.ue_mbl;B&&c&&c.cnt&&!m&&(g+=c.cnt());m?e("wb",b,2):"ld"==l&&(a.lid=I(C));for(y in a.sc)if(1==e("wb",y))break;if(m){if(a.s)return;g=z(g,null,n)}else c=z(g,null,n),c!=g&&(c=r(c),a.b=c),t&&(g+=t),g=z(g,b||a.id,n);g=r(g);if(a.b||m)for(y in a.sc)2==e("wb",y)&&delete a.sc[y];y=0;B&&a._rt&&(g+="&rt="+a._rt());t=k.csa;if(!m&&t)for(h in n=e("t",b)||{},c=t("PageTiming"),n)n[x](h)&&c("mark",X[h]||h,n[h]);m||(a.s=0,(h=d.ue_err)&&0<h.ec&&h.pec<h.ec&&(h.pec=h.ec,g+="&ec="+h.ec+
"&ecf="+h.ecf),y=e("ctb",b),"ld"!==l||b||a.markers?a.markers&&a.isl&&!m&&b&&G(a.markers,e("t",b)):(a.markers={},G(a.markers,e("t",b))),e("t",b,{}));B&&a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),u.csmtags=a.tag(),a.tag=T());h=a.viz||[];n=h.length;B&&n&&(h=h.splice(0,n),g+="&viz="+h.join("|"),u.viz=h);w(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,u.pty=d.ue_pty,u.spty=d.ue_spty,u.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!B||!a._ui||b&&
b!=C||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;v(g,l,y,m,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));m||(u.lob=d.ue_lob||"0",u.browserData=g,(b=t&&t("UEData"))&&b("log",u))}}function ha(a){var b=k.ue_csm_markers||{},c;for(c in b)b[x](c)&&F(c,a,A,b[c])}function D(a,b,c){c=c||k;if(c[$])c[$](a,b,!1);else if(c[aa])c[aa]("on"+a,b)}function Y(a,b,c){c=c||k;if(c[ba])c[ba](a,b,!1);else if(c[ca])c[ca]("on"+a,b)}function da(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,W(a))}}
var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};k.chrome?(D(L,a),P.push(a)):e[L]=d.onUl;for(f in e)e[x](f)&&V(0,k,f,e[f]);d.ue_viz&&ue_viz();D("load",d.onLd);F("ue")}function ga(e,b,c,f,p){var v=d.ue_mbl,r=k.csa,m=r&&r("SPA"),r=r&&r("PageTiming");v&&v.ajax&&v.ajax(b,c);m&&r&&(e={requestId:e,transitionType:"soft"},"string"===typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof p&&(e.subPageType=p,d.ue_spty=p),m("newPage",e),r("mark","transitionStart",b));a.tag("ajax-transition")}
d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=k.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.348446.0";a.paused=!1;var x="hasOwnProperty",L="beforeunload",O="on"+L,$="addEventListener",ba="removeEventListener",aa="attachEvent",ca="detachEvent",X={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},K=k.Date,H=k.performance||
k.webkitPerformance,f=(H||{}).timing,E=(H||{}).navigation,Q=(f||{}).navigationStart,p=d.ue_fpf,U=0,Z=0,P=[],J=0,A;a.oid=I(a.id);a.lid=I(a.id);a._t0=a.t0;a.tag=T();a.ifr=k.top!==k.self||k.frameElement?1:0;a.markers=null;a.attach=D;a.detach=Y;if("000-0000000-8675309"===d.ue_sid){var ea=N("cdn-rid"),fa=N("session-id");ea&&fa&&S(ea,fa,"cdn")}d.uei=da;d.ueh=V;d.ues=e;d.uet=F;d.uex=W;a.reset=S;a.pause=function(d){a.paused=d};da()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");

ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);



var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
</script>
<!-- 4wnx8qt9ur6o -->
<script>window.ue && ue.count && ue.count('CSMLibrarySize', 10684)</script>
<!-- sp:end-feature:csm:head-open-part2 -->
<!-- sp:feature:aui-assets -->
<link href="https://m.media-amazon.com/images/I/21uDPuQuYwL._RC|51SvmD+jTBL.css_.css?AUIClients/AmazonUI" rel="stylesheet">
<link href="https://m.media-amazon.com/images/I/11WsGYSItxL._RC|01DE6WSvLKL.css,41ixaNR85ML.css,3182OVlP7IL.css,21JMC7OC91L.css,01xH+fhFIJL.css,0168Xo81wHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21D3IemrALL.css,11pDJV08stL.css,51yqRfvysvL.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11FeoxrgiyL.css,21TxBPhrLyL.css,01rSTIgNJIL.css,21Dt9D2TuML.css,31GD5I7tbCL.css,01i092IYHUL.css,01oaPOLX+-L.css,31Qk3MvcMIL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21GcfcmbahL.css,21OD8FuBraL.css,11XozyxiH7L.css,21n1oEPZnHL.css,11HVvPbE6JL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11TZSntL0oL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31un+UKeIeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#not-trident" rel="stylesheet">
<script>
(function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(c,e,I,B){"use strict";c._pd=function(){var a,u;return function(C,f,h,k,b,D,v,E,F){function w(d){try{return d()}catch(J){return!1}}function l(){if(m){var d={w:c.innerWidth||b.clientWidth,h:c.innerHeight||b.clientHeight};5<Math.abs(d.w-q.w)||50<d.h-q.h?(q=d,n=4,(d=a.mobile||a.tablet?450<d.w&&d.w>d.h:1250<=d.w)?k(b,"a-ws"):b.className=v(b,"a-ws")):0<n&&(n--,x=setTimeout(l,16))}}function G(d){(m=d===B?!m:!!d)&&l()}function H(){return m}if(!u){u=!0;var r=function(){var d=["O","ms","Moz","Webkit"],
c=e.createElement("div");return{testGradients:function(){return!0},test:function(a){var b=a.charAt(0).toUpperCase()+a.substr(1);a=(d.join(b+" ")+b+" "+a).split(" ");for(b=a.length;b--;)if(""===c.style[a[b]])return!0;return!1},testTransform3d:function(){return!0}}}(),y=b.className,z=/(^| )a-mobile( |$)/.test(y),A=/(^| )a-tablet( |$)/.test(y);a={audio:function(){return!!e.createElement("audio").canPlayType},video:function(){return!!e.createElement("video").canPlayType},canvas:function(){return!!e.createElement("canvas").getContext},
svg:function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in e.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!c.history||!c.history.pushState)},webworker:function(){return!!c.Worker},autofocus:function(){return"autofocus"in e.createElement("input")},
inputPlaceholder:function(){return"placeholder"in e.createElement("input")},textareaPlaceholder:function(){return"placeholder"in e.createElement("textarea")},localStorage:function(){return"localStorage"in c&&null!==c.localStorage},orientation:function(){return"orientation"in c},touch:function(){return"ontouchend"in e},gradients:function(){return r.testGradients()},hires:function(){var a=c.devicePixelRatio&&1.5<=c.devicePixelRatio||c.matchMedia&&c.matchMedia("(min-resolution:144dpi)").matches;E("hiRes"+
(z?"Mobile":A?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return r.testTransform3d()},touchScrolling:function(){return f(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return f(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!f(/trident|Edge/i)},android:function(){return f(/android.([1-9]|[L-Z])/i)&&!f(/trident|Edge/i)},mobile:function(){return z},
tablet:function(){return A},rtl:function(){return"rtl"===b.dir}};for(var g in a)a.hasOwnProperty(g)&&(a[g]=w(a[g]));for(var t="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),p=0;p<t.length;p++)a[t[p]]=w(function(){return r.test(t[p])});var m=!0,x=0,q={w:0,h:0},n=4;l();h(c,"resize",function(){clearTimeout(x);n=4;l()});b.className=v(b,"a-no-js");k(b,"a-js");!f(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||c.navigator.standalone||f(/safari/i)||k(b,"a-ember");
h=[];for(g in a)a.hasOwnProperty(g)&&a[g]&&h.push("a-"+g.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));k(b,h.join(" "));b.setAttribute("data-aui-build-date",F);C.register("p-detect",function(){return{capabilities:a,localStorage:a.localStorage&&D,toggleResponsiveGrid:G,responsiveGridEnabled:H}});return a||{}}}}()})(window,document,Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===
d||"require"===d)a.P.error('"module" or "require" injection is not supported.');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with '@amzn/'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,C,D){function K(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function L(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function p(a,b,c,f){b=b&&c?b+a+c:b||c;return f?p(a,b,f):b}function y(a,b,c){try{Object.defineProperty(a,b,{value:c,writable:!1})}catch(f){a[b]=c}return c}function M(a,b){a.className=
N(a,b)+" "+b}function N(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function aa(a,b,c){var f=c=a.length,e=function(){f--||(E.push(b),F||(m?m.set(z):setTimeout(z,0),F=!0))};for(e();c--;)O[a[c]]?e():(u[a[c]]=u[a[c]]||[]).push(e)}function ba(a,b,c,f,e){var d=h.createElement(a?"script":"link");x(d,"error",f);e&&x(d,"load",e);a?(d.type="text/javascript",d.async=!0,c&&/AUIClients|images[/]I/.test(b)&&d.setAttribute("crossorigin","anonymous"),d.src=b):(d.rel="stylesheet",
d.href=b);h.getElementsByTagName("head")[0].appendChild(d)}function P(a,b){return function(c,f){function e(){ba(b,c,d,function(b){G?q("resource_unload"):d?(d=!1,q("resource_retry"),e()):(q("resource_error"),a.log("Asset failed to load: "+c));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},f)}if(Q[c])return!1;Q[c]=!0;q("resource_count");var d=!0;return!e()}}function ca(a,b,c){for(var f={name:a,guard:function(c){return b.guardFatal(a,c)},guardTime:function(a){return b.guardTime(a)},
logError:function(c,d,e){b.logError(c,d,e,a)}},e=[],d=0;d<c.length;d++)A.hasOwnProperty(c[d])&&(e[d]=H.hasOwnProperty(c[d])?H[c[d]](A[c[d]],f):A[c[d]]);return e}function v(a,b,c,f,e){return function(d,k){function n(){var a=null;f?a=k:"function"===typeof k&&(q.start=r(),a=k.apply(g,ca(d,h,l)),q.end=r());if(b){A[d]=a;a=d;for(O[a]=!0;(u[a]||[]).length;)u[a].shift()();delete u[a]}q.done=!0}var h=e||this;"function"===typeof d&&(k=d,d=D);b&&(d=d?d.replace(R,""):"__NONAME__",I.hasOwnProperty(d)&&h.error(p(", reregistered by ",
p(" by ",d+" already registered",I[d]),h.attribution),d),I[d]=h.attribution);for(var l=[],m=0;m<a.length;m++)l[m]=a[m].replace(R,"");var q=w[d||"anon"+ ++da]={depend:l,registered:r(),namespace:h.namespace};d&&ea.hasOwnProperty(d);c?n():aa(l,h.guardFatal(d,n),d);return{decorate:function(a){H[d]=h.guardFatal(d,a)}}}}function S(a){return function(){var b=Array.prototype.slice.call(arguments);return{execute:v(b,!1,a,!1,this),register:v(b,!0,a,!1,this)}}}function J(a,b){return function(c,f){f||(f=c,c=

In [167]:
# create the empty lists to store the scraped data
data = []
print("Data cleared")

Data cleared

In [168]:
for page in range(1,50):

    #paramters to be sent in the get request
    params = {
        "k": "laptops",
        "page": page
    }

    # get response from the server
    response = requests.get(url, headers=headers, params=params)

    # convert the response content to a BeautifulSoup object
    soup = BeautifulSoup(response.content, "html.parser")

    # find all the product items on the page using correct selector
    product_containers = soup.find_all("div", class_="s-result-item")

    # extract the required data from each product container
    for container in product_containers:

        # Step 1: Extract title from h2 tag
        h2_tag = container.find("h2")
        if not h2_tag:
            continue
        
        title = h2_tag.text.strip()
        
        # Skip if title is too short or is a header
        if len(title) < 10 or title in ["Results", "Trending now"]:
            continue

        # Step 2: Extract product price
        price_tag = container.find("span", class_="a-price-whole")
        price = price_tag.text.strip() if price_tag else "N/A"

        # Step 3: Extract product brand (first word)
        match = re.search(r"^([A-Za-z]+)", title)
        brand = match.group(1) if match else "Unknown"

        # Step 4 : Extract the ram form the title using regex GB,ram DDR LPDDR
        match = re.search(r"(\d+GB|RAM\s*(\d+GB)?|DDR\d?\s*(\d+GB)?|LPDDR\d?\s*(\d+GB)?)", title, re.IGNORECASE)
        ram = match.group(1) if match else "N/A"

        # Step 5 : Extract the SSD storage from the title using reges
        match = re.search(r"(\d+)\s*(GB|TB)\s*(?:SSD|Storage|HDD)", title, re.IGNORECASE)
        ssd_storage = f"{match.group(1)}{match.group(2)}" if match else "N/A"
        
        #Step 6 : Extract the Color from the title using regex
        match = re.search(r"\b(Black|White|Silver|Gray|Grey|Red|Blue|Green|Yellow|Pink|Purple|Gold|Bronze|Rose Gold|Indigo|Glacier)\b", title, re.IGNORECASE)
        color = match.group(1) if match else "N/A"

        # Step 7: Extract the processor (Intel, AMD, Apple M/A chip, Snapdragon, MediaTek, etc)
        processor = "N/A"
        # Try to match Apple M series (M1, M2, M3, M4, M5, etc.)
        match = re.search(r"Apple\s+M(\d+)", title, re.IGNORECASE)
        if match:
            processor = f"Apple M{match.group(1)}"
        else:
            # Try to match Apple A series (A18, A17, A16, etc.)
            match = re.search(r"Apple\s+A(\d+)", title, re.IGNORECASE)
            if match:
                processor = f"Apple A{match.group(1)}"
            else:
                # Try other processor keywords
                processor_keywords = ["Intel", "AMD", "Snapdragon", "MediaTek", "Celeron"]
                for keyword in processor_keywords:
                    if re.search(rf"\b{keyword}\b", title, re.IGNORECASE):
                        processor = keyword
                        break
        
        # Step 8: Extract the OS from the title using regex
        os = "N/A"
        # Check for MacBook/macOS first (Apple specific)
        if re.search(r"\b(MacBook|macOS|Mac OS)\b", title, re.IGNORECASE):
            os = "MacOS"
        # Check for Apple processors (M or A series means MacOS)
        elif re.search(r"\bApple\s+[MA]\d+\b", title, re.IGNORECASE):
            os = "MacOS"
        # Check for Windows variations
        elif re.search(r"\b(Windows|Win\s*11|Win11|Win\s*10|Win10)\b", title, re.IGNORECASE):
            os = "Windows"
        # Check for other OS keywords
        else:
            OS_keywords = ["Linux", "Chrome OS", "Android", "iOS"]
            for keyword in OS_keywords:
                if re.search(rf"\b{keyword}\b", title, re.IGNORECASE):
                    os = keyword
                    break
            
        # Step 9: Extract the Rating from the container
        rating = "N/A"
        # Try multiple methods to find rating
        # Method 1: Look for i-star span
        rating_span = container.find("span", class_=lambda x: x and "i-star" in str(x).lower() if x else False)
        
        # Method 2: Look for aria-label attribute with rating
        if not rating_span:
            rating_span = container.find("span", {"aria-label": lambda x: x and "out of 5" in str(x).lower() if x else False})
        
        # Method 3: Look for a-icon-star class
        if not rating_span:
            rating_span = container.find("i", class_=lambda x: x and "a-icon-star" in str(x).lower() if x else False)
        
        if rating_span:
            # Try to get rating from aria-label
            aria_label = rating_span.get("aria-label")
            if aria_label:
                match = re.search(r"(\d+\.?\d*)\s*out of 5", aria_label)
                if match:
                    rating = match.group(1)
            else:
                # Try to get from text
                rating_text = rating_span.text.strip() if rating_span else ""
                match = re.search(r"(\d+\.?\d*)", rating_text)
                if match:
                    rating = match.group(1) 


        # Append the extracted data to the list
        data.append({
            "title": title,
            "price": price,
            'brand' : brand,
            'ram' : ram,
            'ssd_storage' : ssd_storage,
            'color' : color,
            'processor' : processor,
            'os' : os,
            'rating' : rating
        })

print("Total items scraped:", len(data))

Total items scraped: 1115

In [169]:
# print the scraped data in a structured format
for item in data:
    print(f"Title: {item['title']}")
    print(f"Price: {item['price']}")
    print(f"Brand: {item['brand']}")
    print(f"RAM: {item['ram']}")
    print(f"SSD Storage: {item['ssd_storage']}")
    print(f"Color: {item['color']}")
    print(f"Processor: {item['processor']}")
    print(f"OS: {item['os']}")
    print(f"Rating: {item['rating']}")
    print("-" * 40)

Title: HP Smartchoice Omnibook 5 OLED (Previously Pavilion), Snapdragon X Processor (16GB LPDDR5x,1TB SSD) 2K OLED,16''/40.6cm, Win11, M365(1yr)*Office24, Glacier Silver, 1.59kg, fb0001QU,Next-Gen AI Laptop
Price: 67,793
Brand: HP
RAM: 16GB
SSD Storage: 1TB
Color: Glacier
Processor: Snapdragon
OS: Windows
Rating: 4.2
----------------------------------------
Title: HP Omnibook 3, Snapdragon X Processor, 45 TOPS (16GB LPDDR5x, 512GB SSD) 2K, WUXGA, IPS, 14''/35.6cm, Win 11, Office 24, Silver, 1.4kg, hz0026QU, FHD IR Camera, 42% Lighter mini GaN Charger, AI Laptop
Price: 73,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: Snapdragon
OS: Windows
Rating: 3.0
----------------------------------------
Title: Acer Smartchoice Aspire One, AMD Ryzen 3-7320U, 8GB LPDDR5 RAM/ 256GB SSD, 14.0"/35.56cm TN HD Display, Win 11 Home, Pure Silver, 1.48KG, A114-43, Thin and Light Laptop
Price: 39,990
Brand: Acer
RAM: 8GB
SSD Storage: 256GB
Color: Silver
Processor: AMD
OS: Windows
Rating: 5.0
----------------------------------------
Title: Dell 15 (Previously Inspiron) Laptop, 14th Gen Intel Core i3/Core 3 100U Processor, 8GB DDR4, 512 SSD, 15.6" FHD 120Hz IPS 250 nit Display, Win 11 + Office H&S 2024, Carbon Black, Thin & Light 1.63Kg
Price: 44,990
Brand: Dell
RAM: 8GB
SSD Storage: N/A
Color: Black
Processor: Intel
OS: Windows
Rating: 4.1
----------------------------------------
Title: ASUS TUF A15 (2025), AMD Ryzen 7 7445HS,RTX 3050-4GB,75W TGP,16GB DDR5(Upgradeable Upto 64GB) 512GB SSD,FHD,15.6",144Hz,RGB Keyboard,Windows 11,Graphite Black,2.3 Kg FA506NCG-HN199W, Gaming Laptop
Price: 68,990
Brand: ASUS
RAM: 4GB
SSD Storage: 512GB
Color: Black
Processor: AMD
OS: Windows
Rating: 4.2
----------------------------------------
Title: HP Smartchoice Omnibook 5 OLED (Previously Pavilion), Snapdragon X Processor (16GB LPDDR5x,1TB SSD) 2K OLED,16''/40.6cm, Win11, M365(1yr)*Office24, Glacier Silver, 1.59kg, fb0001QU,Next-Gen AI Laptop
Price: 67,793
Brand: HP
RAM: 16GB
SSD Storage: 1TB
Color: Glacier
Processor: Snapdragon
OS: Windows
Rating: 4.2
----------------------------------------
Title: Lenovo ThinkBook 16, Intel Core Ultra 9 185H, 16GB RAM, 512GB SSD, WUXGA IPS 16” (40.64cm), Win 11 Home, Arctic Grey, 1.7Kg, 21SKA0J5IG, Fingerprint, Backlit, 300 Nits, 1Y Warranty, AI Powered Laptop
Price: 94,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: Intel
OS: Windows
Rating: 5.0
----------------------------------------
Title: HP 14, Intel Core 13th Generation Intel Core i7-1355U (16GB DDR4, 512GB SSD), Micro-Edge, Anti-Glare, FHD, 14''/35.6cm, Win11, M365* Office24, Silver, 1.4kg, EP0159TU, FHD Camera, Backlit Laptop
Price: 79,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: Intel
OS: Windows
Rating: 5.0
----------------------------------------
Title: Lenovo Yoga Slim 7 Aura Edition Intel Evo Core Ultra 5 226V (16GB RAM/1TB SSD/14 (35.5cm)/WUXGA OLED/Copilot+ PC/Windows 11/Office Home 2024/1Yr ADP Free/Grey/1.19Kg), 83JX005FIN AI Laptop
Price: 1,04,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 1TB
Color: Grey
Processor: Intel
OS: Windows
Rating: 4.1
----------------------------------------
Title: Primebook 2 Pro (2026) | 8GB RAM, 128GB UFS Storage | 14.1-Inch FHD IPS Display | 14 Hours Battery | MediaTek Helio G99 | Android 15 (PrimeOS 3.0) | Backlit Keyboard | in-Built AI (Gray)
Price: 25,990
Brand: Primebook
RAM: 8GB
SSD Storage: N/A
Color: Gray
Processor: MediaTek
OS: Android
Rating: 4.4
----------------------------------------
Title: BKN® Mini Premium Metal Folding Portable Laptop Stand Non-Slip Base Tabletop Risers for 10-17 Inch Laptop & Keyboard & Tablet (Pack of 2pcs)
Price: 267
Brand: BKN
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: 4.2
----------------------------------------
Title: More results
Price: N/A
Brand: More
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: N/A
----------------------------------------
Title: ASUS Vivobook 15, Smartchoice,Intel Core i5 13th Gen 13420H,16GB RAM, 512GB SSD, FHD 15.6",Windows 11, Office Home 2024, Quiet Blue, 1.70 kg, X1502VA-BQ836WS,Intel UHD iGPU, M365 Basic (1Year)* Laptop
Price: 59,990
Brand: ASUS
RAM: 16GB
SSD Storage: 512GB
Color: Blue
Processor: Intel
OS: Windows
Rating: 4.2
----------------------------------------
Title: Apple 2026 MacBook Neo 13″ Laptop with A18 Pro chip: Built for AI and Apple Intelligence, Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, 1080p FaceTime HD Camera; Silver
Price: 63,990
Brand: Apple
RAM: 8GB
SSD Storage: 256GB
Color: Silver
Processor: N/A
OS: MacOS
Rating: 4.8
----------------------------------------
Title: HP 15, AMD Ryzen 5 7520U,(16GB LPDDR5, 512GB SSD), Anti-Glare, Micro-Edge, FHD, 15.6''/39.6cm, Win 11, Office 24,M365 Basic(1yr)*,Silver, 1.59kg, fc0690au, FHD Camera, Backlit KB Laptop
Price: 54,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: ASUS Vivobook 15 (2026),Intel Core 3 100U (14th Gen),Intel iGPU, 8GB/512GB, FHD, 15.6"(39.6 cm),Windows 11 Home,M365 Basic(1 Year)* Office 2024,Quiet Blue,1.7 Kg, X1504VAP-BQ1322WS,Thin & Light Laptop
Price: 53,990
Brand: ASUS
RAM: 8GB
SSD Storage: N/A
Color: Blue
Processor: Intel
OS: Windows
Rating: N/A
----------------------------------------
Title: HP 15, 13th Gen Intel Core i3-1315U Laptop (8GB DDR4,512GB SSD) Anti-Glare, Micro-Edge,15.6''/39.6cm, FHD, Win11,M365 Basic(1yr),Office Home24, Silver,1.59kg, FHD Camera w/Privacy Shutter, fd0569TU
Price: 49,880
Brand: HP
RAM: 8GB
SSD Storage: 512GB
Color: Silver
Processor: Intel
OS: Windows
Rating: 4.2
----------------------------------------
Title: Lenovo V15 G4 (2024), AMD Ryzen 3 7320U Quad Core - (8GB/512GB SSD/AMD Radeon Graphics/Windows 11 Home) Thin and Light Business Laptop/15.6" FHD Display/Arctic Grey/1.57 kg/MS Office 2021
Price: 49,890
Brand: Lenovo
RAM: 8GB
SSD Storage: 512GB
Color: Grey
Processor: AMD
OS: Windows
Rating: 3.9
----------------------------------------
Title: Lenovo ThinkBook 16, AMD Ryzen 5 7535HS, 16GB RAM, 512GB SSD, WUXGA IPS 16", Windows 11 Home, Office 2024, 1.7kg, 21MWA0BSIN, Backlit Keyboard, Fingerprint, 300 Nits, 1Y Warranty, Aluminium Top Laptop
Price: 61,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: N/A
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: Dell 15 Smart Choice (Previously Inspiron), 13th Gen Intel Core i5-1334U (16GB RAM, 1TB SSD) FHD, 15.6"/39.62cm, Windows 11 MSO'24, Silver, 1.62kg, 12 Month McAfee, Backlit KB, Thin & Light Laptop
Price: 66,990
Brand: Dell
RAM: 16GB
SSD Storage: 1TB
Color: Silver
Processor: Intel
OS: Windows
Rating: 3.8
----------------------------------------
Title: Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8GB LPDDR5 Ram, 512 GB SSD PCIe, Windows 11 Lifetime Validity,15.6" FHD Screen, AMD Radeon 610M, Silver, 1 Year Brand Warranty
Price: 42,999
Brand: Lenovo
RAM: 8GB
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: HP 15 Smartchoice, 13th Gen Intel Core i3-1315U(8GB DDR4,512GB SSD) FHD, Anti-Glare, Micro-Edge, 15.6''/39.6cm, Win11, M365(1yr)*Office24, Silver,1.59kg, fd0572TU, FHD Camera w/Shutter, Backlit Laptop
Price: 51,990
Brand: HP
RAM: 8GB
SSD Storage: 512GB
Color: Silver
Processor: Intel
OS: Windows
Rating: 4.1
----------------------------------------
Title: Acer Smartchoice Aspire One, Intel Core Celeron N4500, Office 2024 + M365 Basic, 12GB LPDDR4X / 512GB SSD, 14.0"/35.56cm TN HD Display, Win 11 Home, Pure Silver, 1.3KG, A114-45, Thin and Light Laptop
Price: 38,990
Brand: Acer
RAM: 12GB
SSD Storage: 512GB
Color: Silver
Processor: Intel
OS: Windows
Rating: 3.3
----------------------------------------
Title: HP Smartchoice Victus, AMD Ryzen 7 7445HS, 6GB RTX 3050, 16GB DDR5(Upgradeable) 512GB SSD, FHD, 144Hz, 300 nits, 15.6''/39.6cm, Win 11, M365* Office24, Blue, 2.29kg, fb3134AX/3120ax, Gaming Laptop
Price: 78,990
Brand: HP
RAM: 6GB
SSD Storage: 512GB
Color: Blue
Processor: AMD
OS: Windows
Rating: 4.1
----------------------------------------
Title: Lenovo IdeaPad 1 AMD Ryzen 5 5500U 15.6" HD Thin and Light Laptop (8GB RAM/512GB SSD/Windows 11 Home/Office Home 2024/1 Year ADP Free/Grey/1.6Kg), 82R4011MIN
Price: 49,950
Brand: Lenovo
RAM: 8GB
SSD Storage: 512GB
Color: Grey
Processor: AMD
OS: Windows
Rating: 4.1
----------------------------------------
Title: Apple 2026 MacBook Neo 13″ Laptop with A18 Pro chip: Built for AI and Apple Intelligence, Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, 1080p FaceTime HD Camera; Indigo
Price: 65,000
Brand: Apple
RAM: 8GB
SSD Storage: 256GB
Color: Indigo
Processor: N/A
OS: MacOS
Rating: 4.8
----------------------------------------
Title: EBook 11.6" HD Laptop | Best Student & Office Work Laptop | Celeron N4020 | 4GB DDR4 | 128GB eMMC + M.2 SSD Expandable Slot | Win 11 Home |31Wh Battery | UHD Graphics 600 | Black
Price: 11,990
Brand: EBook
RAM: 4GB
SSD Storage: N/A
Color: Black
Processor: Celeron
OS: Windows
Rating: 3.4
----------------------------------------
Title: ASUS Vivobook S14,Smartchoice,AMD Ryzen AI 7 350,16GB RAM,1TB SSD,OLED, 14",Windows 11, Office24, M365 Basic (1Yr)*,Cool Silver,1.4Kg,M3407KA-SF048WS,50Tops,Metallic Design,Next-Gen AI Laptop,Copilot+
Price: 75,990
Brand: ASUS
RAM: 16GB
SSD Storage: 1TB
Color: Silver
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: HP 15, AMD Ryzen 5 7520U (16GB DDR4, 512GB SSD) FHD, Anti-Glare, Micro-Edge, 15.6''/39.6cm, Win11, M365 Basic(1yr), Offic24, Silver,1.59kg, fc0806AU, FHD Camera w/Privacy Shutter, Backlit Laptop
Price: 63,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: Windows
Rating: N/A
----------------------------------------
Title: COSMUS Agility Convertible Backpack Messenger Bag for up to 16-Inch Laptop
Price: 1,799
Brand: COSMUS
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: 4.3
----------------------------------------
Title: Related searches
Price: N/A
Brand: Related
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: N/A
----------------------------------------
Title: Need help?
Price: N/A
Brand: Need
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: N/A
----------------------------------------
Title: Lenovo V15 G4 (2024), AMD Ryzen 3 7320U Quad Core - (8GB/512GB SSD/AMD Radeon Graphics/Windows 11 Home) Thin and Light Business Laptop/15.6" FHD Display/Arctic Grey/1.57 kg/MS Office 2021
Price: 49,890
Brand: Lenovo
RAM: 8GB
SSD Storage: 512GB
Color: Grey
Processor: AMD
OS: Windows
Rating: 3.9
----------------------------------------
Title: HP Omnibook 3, Snapdragon X Processor, 45 TOPS (16GB LPDDR5x, 512GB SSD) 2K, WUXGA, IPS, 14''/35.6cm, Win 11, Office 24, Silver, 1.4kg, hz0026QU, FHD IR Camera, 42% Lighter mini GaN Charger, AI Laptop
Price: 73,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: Snapdragon
OS: Windows
Rating: 3.0
----------------------------------------
Title: 𝗗𝗲𝗹𝗹Laptop Model 5420 | 𝗜𝗡𝗧𝗘𝗟i5 11th Gen Processor |8GB DDR4 RAM |256GB SSD |14" FHD Display | Win10 | A+ Condition Laptop (Refab)
Price: 37,490
Brand: Unknown
RAM: 8GB
SSD Storage: 256GB
Color: N/A
Processor: N/A
OS: Windows
Rating: 5.0
----------------------------------------
Title: Lenovo IdeaPad Slim 3 12th Gen Intel Core i5-12450H 15.6 Inch (39.6cm) FHD Thin & Light Laptop (16GB/512GB SSD/Windows 11/Office Home 2024/3months Game Pass/Arctic Grey/1.62Kg), 83ER00MCIN
Price: 64,580
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: Intel
OS: Windows
Rating: 4.5
----------------------------------------
Title: HP Smartchoice Omnibook 5 OLED (Previously Pavilion), Snapdragon X Processor (16GB LPDDR5x,1TB SSD) 2K OLED,16''/40.6cm, Win11, M365(1yr)*Office24, Glacier Silver, 1.59kg, fb0001QU,Next-Gen AI Laptop
Price: 67,793
Brand: HP
RAM: 16GB
SSD Storage: 1TB
Color: Glacier
Processor: Snapdragon
OS: Windows
Rating: 4.2
----------------------------------------
Title: Highly rated
Price: 67,793
Brand: Highly
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: 4.2
----------------------------------------
Title: HP Smartchoice Omnibook 5 OLED (Previously Pavilion), Snapdragon X Processor (16GB LPDDR5x,1TB SSD) 2K OLED,16''/40.6cm, Win11, M365(1yr)*Office24, Glacier Silver, 1.59kg, fb0001QU,Next-Gen AI Laptop
Price: 67,793
Brand: HP
RAM: 16GB
SSD Storage: 1TB
Color: Glacier
Processor: Snapdragon
OS: Windows
Rating: 4.2
----------------------------------------
Title: Lenovo ThinkBook 16, AMD Ryzen 5 7535HS, 16GB RAM, 512GB SSD, WUXGA IPS 16", Windows 11 Home, Office 2024, 1.7kg, 21MWA0BSIN, Backlit Keyboard, Fingerprint, 300 Nits, 1Y Warranty, Aluminium Top Laptop
Price: 61,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: N/A
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: Primebook 2 Pro (2026) | 8GB RAM, 128GB UFS Storage | 14.1-Inch FHD IPS Display | 14 Hours Battery | MediaTek Helio G99 | Android 15 (PrimeOS 3.0) | Backlit Keyboard | in-Built AI (Gray)
Price: 25,990
Brand: Primebook
RAM: 8GB
SSD Storage: N/A
Color: Gray
Processor: MediaTek
OS: Android
Rating: 4.4
----------------------------------------
Title: Lenovo IdeaPad Slim 5 Ryzen 7 7735HS (16GB RAM/512GB SSD/Integrated AMD Radeon 680M Graphics/WUXGA IPS Display/13.3" (33.7cm)/Windows 11/Office Home 2024/Backlit KB/Grey/1.15Kg), 83J2000HIN Laptop
Price: 77,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: Lenovo Ideapad Slim 3, 13th Gen Intel Core i7 13620H, 16GB RAM, 512GB SSD, WUXGA IPS, 15.3"/38.8cm, Win 11, Office 2024, Top Metal Cover Grey, 1.6Kg, 83K100CJIN/S1IN, Backlit KB, Laptop
Price: 79,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: Intel
OS: Windows
Rating: 4.1
----------------------------------------
Title: More results
Price: N/A
Brand: More
RAM: N/A
SSD Storage: N/A
Color: N/A
Processor: N/A
OS: N/A
Rating: N/A
----------------------------------------
Title: Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD Laptop, AMD Graphics, 16GB DDR5 5500Mhz Ram, 512GB SSD NVMe, Windows 11, Dolby Audio, Arctic Grey, 1 Year Onsite Brand Warranty
Price: 54,790
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: Dell 15, Smart Choice AMD Ryzen 7-7730U, 16GB DDR4, 512GB SSD, FHD, 15.6"/39.6cm, Windows 11, Microsoft Office Home 2024, Silver, 1.63Kg, 120Hz 250nits, AMD Radeon Graphics, Thin & Light Laptop
Price: 58,490
Brand: Dell
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: Windows
Rating: 3.5
----------------------------------------
Title: HP 14, AMD Ryzen 7 7730U (16GB DDR4, 512GB SSD) FHD, Anti-Glare, Micro-Edge, 14''/35.6cm, Win11, M365 Basic(1yr), Office Home24, Silver,1.4kg, EM0104AU, FHD Camera w/Privacy Shutter, Backlit Laptop
Price: 63,990
Brand: HP
RAM: 16GB
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: Windows
Rating: 4.8
----------------------------------------
Title: HP Laptop 15 Intel Core i3 13th Gen (8GB|512 GB SSD)/Window 11 Home 15-FD0533TU Laptop (15.6 inch,Natural Silver,1.59 kg, with MS Office
Price: 47,490
Brand: HP
RAM: 8GB
SSD Storage: 512GB
Color: Silver
Processor: Intel
OS: N/A
Rating: 5.0
----------------------------------------
Title: Lenovo Chromebook Intel Celeron N4500 (4GB RAM/64GB eMMC 5.1/11.6 Inch (29.46cm)/HD Display/2Wx2 Stereo Speakers/HD Camera/Chrome OS/Blue/1.21Kg), 82UY0014HA
Price: 18,990
Brand: Lenovo
RAM: 4GB
SSD Storage: N/A
Color: Blue
Processor: Intel
OS: Chrome OS
Rating: 3.9
----------------------------------------
Title: HP Smartchoice Omnibook 5 OLED (Previously Pavilion), Snapdragon X Processor (16GB LPDDR5x,1TB SSD) 2K OLED,16''/40.6cm, Win11, M365(1yr)*Office24, Glacier Silver, 1.59kg, fb0001QU,Next-Gen AI Laptop
Price: 67,793
Brand: HP
RAM: 16GB
SSD Storage: 1TB
Color: Glacier
Processor: Snapdragon
OS: Windows
Rating: 4.2
----------------------------------------
Title: Lenovo ThinkBook 16, AMD Ryzen 5 7535HS, 16GB RAM, 512GB SSD, WUXGA IPS 16", Windows 11 Home, Office 2024, 1.7kg, 21MWA0BSIN, Backlit Keyboard, Fingerprint, 300 Nits, 1Y Warranty, Aluminium Top Laptop
Price: 61,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: N/A
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: MSI Thin A15, AMD 7th Gen. Ryzen 7 7735HS, 40CM FHD 144Hz Gaming Laptop (16GB/1TB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 3050, GDDR6 4GB/Cosmos Gray/1.8Kg) B7UC-103IN
Price: 65,990
Brand: MSI
RAM: 16GB
SSD Storage: N/A
Color: Gray
Processor: AMD
OS: Windows
Rating: 4.5
----------------------------------------
Title: HP 15 255R G10, AMD Ryzen 5 7535U Hexa Core (6 Core, 12 Threads, 2.9 to Max 4.3 Ghz) (8 GB/512 GB SSD/AMD Radeon Graphics/dos) Thin and Light Laptop(15.6 inch HD Display, Matt Silver, 1.45
Price: 47,590
Brand: HP
RAM: N/A
SSD Storage: 512GB
Color: Silver
Processor: AMD
OS: N/A
Rating: 4.2
----------------------------------------
Title: Apple 2026 MacBook Air 13″ Laptop with M5 chip: AI and Apple Intelligence, 34.46 cm (13.6″) Liquid Retina Display, 16GB Unified Memory, 512GB SSD Storage, 12MP Center Stage Camera, Touch ID; Sky Blue
Price: 1,10,300
Brand: Apple
RAM: 16GB
SSD Storage: 512GB
Color: Blue
Processor: N/A
OS: MacOS
Rating: 4.9
----------------------------------------
Title: Lenovo V14 Intel Core i3 13th Gen 14" FHD (1920x1080) Antiglare 250 Nits Thin and Light Laptop (16GB RAM/512GB SSD/Windows 11 Home/Office Home 2024/Iron Grey/1.43 kg), 83A0A0PCIN
Price: 56,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 512GB
Color: Grey
Processor: Intel
OS: Windows
Rating: 3.7
----------------------------------------
Title: ASUS Vivobook 15, Smartchoice,Intel Core i3 13th Gen 1315U, 12GB RAM, 512GB SSD, FHD 15.6", Win 11, Office 2024, Quiet Blue, 1.7Kg, X1504VA-BQ332WS, Intel UHD iGPU, M365 Basic (1Year)*, 42Whrs Laptop
Price: 51,990
Brand: ASUS
RAM: 12GB
SSD Storage: 512GB
Color: Blue
Processor: Intel
OS: Windows
Rating: 4.3
----------------------------------------
Title: ASUS Chromebook CX1405 (2026), Smartchoice,Intel N50 Processor, Intel UHD iGPU, 8GB RAM, 128GB SSD, FHD, 14" (35.5 cm), Chrome OS, Pure Grey, 1.39 Kg, CX1405CTA-S60622, 42WHrs, Thin & Light Laptop
Price: 36,990
Brand: ASUS
RAM: 8GB
SSD Storage: 128GB
Color: Grey
Processor: Intel
OS: Chrome OS
Rating: 3.7
----------------------------------------
Title: Acer Aspire 3 Laptop Intel Core Celeron N4500 Processor Laptop (8 GB LPDDR4X SDRAM/256 GB SSD/Win11 Home/38 WHR/HD Webcam) A325-45 with 39.63 cm (15.6") HD Display, Pure Silver, 1.5 KG
Price: 36,990
Brand: Acer
RAM: LPDDR4
SSD Storage: 256GB
Color: Silver
Processor: Intel
OS: Windows
Rating: 3.6
----------------------------------------
Title: acer SmartChoice Aspire Lite, AMD Ryzen 5-5625U Processor, 16 GB/512 GB, Full HD, 15.6"/39.62 cm, Windows 11 Home, Steel Gray, 1.59 kg, AL15-41, Metal Body, Thin and Light Laptop
Price: 54,990
Brand: acer
RAM: N/A
SSD Storage: N/A
Color: Gray
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: ASUS Vivobook S14,Smartchoice,AMD Ryzen AI 7 350,16GB RAM,1TB SSD,OLED, 14",Windows 11, Office24, M365 Basic (1Yr)*,Cool Silver,1.4Kg,M3407KA-SF048WS,50Tops,Metallic Design,Next-Gen AI Laptop,Copilot+
Price: 75,990
Brand: ASUS
RAM: 16GB
SSD Storage: 1TB
Color: Silver
Processor: AMD
OS: Windows
Rating: 4.0
----------------------------------------
Title: Lenovo ThinkBook 14, AMD Ryzen 5 220, 16GB RAM, 1TB SSD, WUXGA IPS 14” (35.56cm), Windows 11 Home, Arctic Grey, 1.36Kg, 21V0A01SIG, Fingerprint, Backlit, 400 Nits, 1Y Warranty, Laptop
Price: 77,990
Brand: Lenovo
RAM: 16GB
SSD Storage: 1TB
Color: Grey
Processor: AMD
OS: Windows
Rating: 5.0
----------------------------------------

In [202]:
# make the dataframe from the scraped data
df = pd.DataFrame(data)
df.head()

,title,price,brand,ram,ssd_storage,color,processor,os,rating
0,HP Smartchoice Omnibook 5 OLED (Previously Pav...,"67,793",HP,16GB,1TB,Glacier,Snapdragon,Windows,4.2
1,"HP Omnibook 3, Snapdragon X Processor, 45 TOPS...","73,990",HP,16GB,512GB,Silver,Snapdragon,Windows,3.0
2,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...","39,990",Acer,8GB,256GB,Silver,AMD,Windows,5.0
3,"Dell 15 (Previously Inspiron) Laptop, 14th Gen...","44,990",Dell,8GB,N/A,Black,Intel,Windows,4.1
4,"ASUS TUF A15 (2025), AMD Ryzen 7 7445HS,RTX 30...","68,990",ASUS,4GB,512GB,Black,AMD,Windows,4.2

# Data Preprocessing on the scrap data

In [203]:
# check the info of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        1115 non-null   object
 1   price        1115 non-null   object
 2   brand        1115 non-null   object
 3   ram          1115 non-null   object
 4   ssd_storage  1115 non-null   object
 5   color        1115 non-null   object
 6   processor    1115 non-null   object
 7   os           1115 non-null   object
 8   rating       1115 non-null   object
dtypes: object(9)
memory usage: 78.5+ KB

In [204]:
# check the shape of the dataframe
df.shape

(1115, 9)

In [205]:
# check the missing values in the dataframe
df.isnull().sum()

title          0
price          0
brand          0
ram            0
ssd_storage    0
color          0
processor      0
os             0
rating         0
dtype: int64

In [206]:
# replace all N/A values with NaN
df.replace("N/A", pd.NA, inplace=True)

In [207]:
# check missing value 
df.isnull().sum()

title            0
price          193
brand            0
ram            317
ssd_storage    387
color          379
processor      306
os             305
rating         264
dtype: int64

In [208]:
#  drop the title column as it is not required for analysis
df.drop("title", axis=1, inplace=True)

In [209]:
df.head()

    price brand   ram ssd_storage    color   processor       os rating
0  67,793    HP  16GB         1TB  Glacier  Snapdragon  Windows    4.2
1  73,990    HP  16GB       512GB   Silver  Snapdragon  Windows    3.0
2  39,990  Acer   8GB       256GB   Silver         AMD  Windows    5.0
3  44,990  Dell   8GB        <NA>    Black       Intel  Windows    4.1
4  68,990  ASUS   4GB       512GB    Black         AMD  Windows    4.2

In [210]:
# all columns are first letter title 
df.columns = df.columns.str.title()

In [211]:
df.head()

    Price Brand   Ram Ssd_Storage    Color   Processor       Os Rating
0  67,793    HP  16GB         1TB  Glacier  Snapdragon  Windows    4.2
1  73,990    HP  16GB       512GB   Silver  Snapdragon  Windows    3.0
2  39,990  Acer   8GB       256GB   Silver         AMD  Windows    5.0
3  44,990  Dell   8GB        <NA>    Black       Intel  Windows    4.1
4  68,990  ASUS   4GB       512GB    Black         AMD  Windows    4.2

In [212]:
# Rename multiple columns
df = df.rename(columns = {'Ram' : 'RAM', 'Ssd_Storage' : 'SSD_Storage', 'Os' : 'OS',})

In [213]:
df.head()

    Price Brand   RAM SSD_Storage    Color   Processor       OS Rating
0  67,793    HP  16GB         1TB  Glacier  Snapdragon  Windows    4.2
1  73,990    HP  16GB       512GB   Silver  Snapdragon  Windows    3.0
2  39,990  Acer   8GB       256GB   Silver         AMD  Windows    5.0
3  44,990  Dell   8GB        <NA>    Black       Intel  Windows    4.1
4  68,990  ASUS   4GB       512GB    Black         AMD  Windows    4.2

In [214]:
df.head()

    Price Brand   RAM SSD_Storage    Color   Processor       OS Rating
0  67,793    HP  16GB         1TB  Glacier  Snapdragon  Windows    4.2
1  73,990    HP  16GB       512GB   Silver  Snapdragon  Windows    3.0
2  39,990  Acer   8GB       256GB   Silver         AMD  Windows    5.0
3  44,990  Dell   8GB        <NA>    Black       Intel  Windows    4.1
4  68,990  ASUS   4GB       512GB    Black         AMD  Windows    4.2

In [215]:
# handled the SSD storage column 

# replace the 1TB with 1024GB in the SSD storage column
df['SSD_Storage'] = df['SSD_Storage'].str.replace('1TB', '1024GB', regex=False)

# replace GB with empty string and convert to numeric
df['SSD_Storage'] = df['SSD_Storage'].str.replace('GB', '', regex=False)
df['SSD_Storage'] = pd.to_numeric(df['SSD_Storage'], errors='coerce')
df['SSD_Storage']

0       1024.0
1        512.0
2        256.0
3          NaN
4        512.0
         ...
1110     512.0
1111     512.0
1112       NaN
1113       NaN
1114       NaN
Name: SSD_Storage, Length: 1115, dtype: float64